### ISSUE TITLE
The last part doesn't work

### ISSUE THREAD

**Issue by FlyDre** [NetoPedro/Deep-Learning-Push-Up-Counter#2] opened 2020-07-10 14:15 UTC
Sir, I use your model and "test_video.mov" to run the last part: generate a new video, but it seems the text box didn't show. 
So  I am here for your help, are you nice enough to tell me where is wrong? Cannot appreciate you more!

**Comment by NetoPedro** [comment] 2020-07-13 18:03
Hi @FlyDre I believe that the problem is now fixed. Thank you.

**Closed as completed** 2020-07-20 11:04 UTC
